name: Angular CI/CD Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Lint the code
      - name: Lint Code
        run: npm run lint

      # Step 5: Build the Angular app
      - name: Build Angular App
        run: npm run build -- --configuration production

      # Step 6: Run unit tests
      - name: Run Unit Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # Step 7: Upload build artifacts (optional)
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
